version: '3.9'

services:
  redis:
    image: redis:7.0.7
    container_name: redis_db
    restart: always
    ports:
      - '6379:6379'
    env_file: .env
    volumes:
      - ./data:/var/lib/postgres/data

  api:
    build:
      context: .
      dockerfile: short_url_api/Dockerfile
    command: >
      sh -c "cd short_url_api &&
             python manage.py migrate &&
             python manage.py shell"
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - .:/app
